---

- block:
    - when: immich_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: immich_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

  tags:
    - setup-all
    - setup-immich
    - install-all
    - install-immich

- block:
    # If the whole role is disabled or any of its subcomponents are disabled, run the uninstall tasks.
    # They will check what needs to be uninstalled.
    - when: not (immich_enabled and immich_machine_learning_enabled and immich_server_enabled)
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-immich
